### ISSUE TITLE
App crashes on login if cannot connect to server

### ISSUE THREAD

**Issue by cactuspoint** [iommu/CSCI334Project#6]

**Comment by iommu** [comment]
This happens when no server is found, so the solution is just to add error handling to the login

**Comment by cactuspoint** [comment]
Resolved with commit eaa19907c3319446e2cffb136ac2e273b28622c2

**Comment by iommu** [comment]
So I looked at this all of Saturday, and it seems like as of current how we're doing the requests there is no way to handle these exceptions as their thrown, so this needs to be mitigated by running without debugging (or by playing past the throw with the debug controls).

In terms of actual exception handling however it is currently being done (see line 15 of login.dart or signup.dart for examples) so we're good for production

**Comment by cactuspoint** [comment]
Added debug button to bypass login on welcome page in commit 324bc5456160f9c33d6549a7877f8da51bc4ee6b

The button just navigates to the dashboard page.
This is needed for quick texting of other parts of the app, when the server is not running.

It would be good if we can ensure there is error handling (such as default NA values) for ui elements that are populated from the server.

**Comment by cactuspoint** [comment]
Added debug button to bypass login on welcome page in commit 324bc54

The button just navigates to the dashboard page.
This can be used for quick testing of other parts of the app, when the server is not running.

It would be good if we can ensure there is error handling (such as default NA values) for ui elements that are populated from the server.
